window.SPACEGLEAM_BLOG_POSTS = [
    {
        slug: 'omiotsuke-android-app-release',
        title: '「御御御付」、Android版アプリを正式リリースしました',
        date: '2026-08-31',
        publishAt: '2026-08-31T00:00:00+09:00',
        status: 'published',
        category: 'Product',
        description: '冷蔵庫の食材から今日の味噌汁を提案するAIレシピアプリ「御御御付（おみおつけ）」のAndroidネイティブアプリを、Google Playにて公開しました。主な機能とダウンロード方法を紹介します。',
        excerpt: 'Web版で提供してきた「御御御付」が、Androidのネイティブアプリとして登場。作る予定のローカル通知や、Web版と共通のアカウント・ランキングに対応しています。',
        url: 'https://spacegleam.co.jp/blog/omiotsuke-android-app-release/',
        thumbnail: '/blog/omiotsuke-android-app-release/ogp.png'
    },
    {
        slug: 'omiotsuke-for-brands',
        title: '食品ECに「今日使う理由」を。AIレシピ接客「御御御付 for Brands」',
        date: '2026-08-24',
        publishAt: '2026-08-24T00:00:00+09:00',
        status: 'published',
        category: 'Product',
        description: '食品ECの商品を、家にある食材に合うレシピとして提案。食品メーカー向けAIレシピ接客「御御御付 for Brands」の仕組み、活用方法、料金を紹介します。',
        excerpt: '商品を知ってもらうだけでなく、「今日使ってみたい」まで届ける。家にある食材から商品を使う理由をつくるAIレシピ接客を紹介します。',
        url: 'https://spacegleam.co.jp/blog/omiotsuke-for-brands/',
        thumbnail: '/blog/omiotsuke-for-brands/ogp.png'
    },
    {
        slug: 'website-mcp-chatgpt-integration',
        title: '自社WebサイトをChatGPTから使えるようにするには？MCP対応でできること・導入方法・費用を解説',
        date: '2026-08-13',
        publishAt: '2026-08-13T09:00:00+09:00',
        status: 'published',
        category: 'Development',
        description: '自社WebサイトやWebサービスをChatGPTなどのAIエージェントから利用できるようにするMCP対応について解説。できること、APIとの違い、導入方法、開発費用、向いている企業を、Remote MCPを本番運用するSPACE GLEAMが紹介します。',
        excerpt: '自社WebサイトやWebサービスをChatGPTなどのAIエージェントから利用できるようにするMCP対応について解説。できること、APIとの違い、導入方法、開発費用を詳しく紹介します。',
        url: 'https://spacegleam.co.jp/blog/website-mcp-chatgpt-integration/',
        thumbnail: '/blog/website-mcp-chatgpt-integration/card.png?v=20260809-v3'
    },
    {
        slug: 'chatgpt-remote-mcp-web-agent',
        title: 'ChatGPTからWebサイトの機能を直接使う。SPACE GLEAMがRemote MCPを実装・実機検証',
        date: '2026-08-10',
        publishAt: '2026-08-10T09:00:00+09:00',
        status: 'published',
        category: 'Development',
        description: 'SPACE GLEAMはコーポレートサイトにRemote MCP Serverを実装。ChatGPTからサービス検索、AI開発診断、案件要件の整理まで直接実行できることを実機検証しました。MCPの仕組み、ChatGPTへの登録方法、実際の使い方まで解説します。',
        excerpt: 'SPACE GLEAMはコーポレートサイトにRemote MCP Serverを実装。ChatGPTからサービス検索、AI開発診断、案件要件の整理まで直接実行できることを実機検証しました。',
        url: 'https://spacegleam.co.jp/blog/chatgpt-remote-mcp-web-agent/',
        thumbnail: '/blog/chatgpt-remote-mcp-web-agent/card.png'
    },
    {
        slug: 'ai-model-update-resilience',
        title: 'AIの出力は揺れる前提で作る。自社SaaSで実装している4つの備え',
        date: '2026-07-28', publishAt: '2026-07-28T00:00:00+09:00', status: 'published', category: 'Development',
        description: '生成AIのモデルは更新され、出力の傾向やフォーマットが変わる可能性があります。DIFFsenseと御御御付（おみおつけ）の実装をもとに、バージョン固定、複数キー名の許容、多段階のJSONパース、フォールバックとキルスイッチといった防御的な工夫を、実際のコードに基づいて紹介します。',
        excerpt: 'LLMの出力は本来ゆらぎがあるものという前提で、DIFFsenseと御御御付の実装がどう作られているかを、実際のコードに基づいて紹介します。',
        url: 'https://spacegleam.co.jp/blog/ai-model-update-resilience/', thumbnail: '/blog/ai-model-update-resilience/card.webp'
    },
    {
        slug: 'ai-system-development-cost',
        title: 'AIシステム開発の費用相場｜料金の内訳・開発期間・予算別の違い',
        date: '2026-07-23',
        publishAt: '2026-07-23T00:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: 'AIシステム開発の費用相場を、開発規模・機能・期間別に解説します。業務自動化、社内システム、生成AIの組み込みなど、予算別に実現できる内容や費用を抑える方法も紹介します。',
        excerpt: 'AIシステム開発の費用相場を、開発規模・機能・期間別に解説します。業務自動化、社内システム、生成AIの組み込みなど、予算別に実現できる内容や費用を抑える方法も紹介します。',
        url: 'https://spacegleam.co.jp/blog/ai-system-development-cost/',
        thumbnail: '/blog/assets/diagnosis-covers/p3.png'
    },
    {
        slug: 'omiotsuke-development-insights',
        title: '冷蔵庫の残り物から今日の味噌汁を。「御御御付」開発の実践知',
        date: '2026-07-22', publishAt: '2026-07-22T00:00:00+09:00', status: 'published', category: 'Development',
        description: '冷蔵庫の残り物写真をGemini APIで解析し、400種の具材から最適な味噌汁を提案する「御御御付（おみおつけ）」。実用に耐えうる画像認識、400種を1つの鍋で仕上げる時間差レシピ構築、そして遊び心あふれる命名アルゴリズムの裏側の実践知を公開します。',
        excerpt: '冷蔵庫の残り物写真をGemini APIで解析し、最適な味噌汁を提案する「御御御付（おみおつけ）」。画像認識のゆらぎ吸収、400種を1鍋で煮る時間差レシピ、遊び心あふれる命名アルゴリズムの設計といった、実運用から得た開発の裏側を解説します。',
        url: 'https://spacegleam.co.jp/blog/omiotsuke-development-insights/', thumbnail: '/blog/omiotsuke-development-insights/card.png'
    },
    {
        slug: 'human-review-ai-workflow',
        title: 'AIに任せきらない業務設計。人の確認を残すべき5つの場面',
        date: '2026-07-16', publishAt: '2026-07-16T10:00:00+09:00', status: 'published', category: 'Development',
        description: 'EU AI Actの透明性義務と経済産業省の民事責任手引きを確認し、人の承認を残す場面、例外キュー、二重実行防止を業務設計として解説します。',
        excerpt: '確認ボタンを付けるだけでは不十分です。DIFFsenseで実装済みの差分比較と、業務システム一般に必要な例外キュー・再実行を区別して解説します。',
        url: 'https://spacegleam.co.jp/blog/human-review-ai-workflow/', thumbnail: '/blog/human-review-ai-workflow/card.webp'
    },
    {
        slug: 'website-ai-sales-mcp',
        title: 'ホームページをAI営業窓口にする。診断・概算・相談をMCPでつなぐ',
        date: '2026-07-15', publishAt: '2026-07-15T10:00:00+09:00', status: 'published', category: 'Development',
        description: '企業サイトの情報をAIから扱うには何が必要か。SPACE GLEAMのコードに実装している5つのMCPツール、公開API、同意付き問い合わせと現在の運用課題を解説します。',
        excerpt: 'サービス検索、ルール型診断、相談メモ、会社概要、同意付き問い合わせ。コードで確認できる5つのMCPツールと、未対応の運用課題を整理します。',
        url: 'https://spacegleam.co.jp/blog/website-ai-sales-mcp/', thumbnail: '/blog/website-ai-sales-mcp/card.webp'
    },
    {
        slug: 'ai-search-ready-corporate-website',
        title: 'AI検索時代、会社はどう選ばれる？ChatGPT・Google AIに伝わる企業サイト',
        date: '2026-07-14', publishAt: '2026-07-14T10:00:00+09:00', status: 'published', category: 'Development',
        description: 'Google AI Mode時代に企業サイトはどう作るべきか。SPACE GLEAMのサイトで採用している本文設計、JSON-LD、llms.txt、公開APIの構成と注意点を解説します。',
        excerpt: 'AIに伝わる企業サイトは何が違うのか。実際の配置とコードを確認できる範囲に限定し、本文・JSON-LD・llms.txt・公開APIの構成を解説します。',
        url: 'https://spacegleam.co.jp/blog/ai-search-ready-corporate-website/', thumbnail: '/blog/ai-search-ready-corporate-website/card.webp'
    },
    {
        slug: 'ai-poc-to-production',
        title: 'AIのPoCは動いたのに、本番導入できない。止まる理由と立て直し方',
        date: '2026-07-13', publishAt: '2026-07-13T10:00:00+09:00', status: 'published', category: 'Development',
        description: 'AIのPoCがデモで終わり、本番導入へ進めない理由を、評価・業務導線・セキュリティ・運用・責任分界から整理。作り直す前の立て直し方を解説します。',
        excerpt: 'デモは動いたのに現場で使われない。AIのPoCが本番へ進めない5つの理由と、既存成果物を活かした現実的な立て直し方を解説します。',
        url: 'https://spacegleam.co.jp/blog/ai-poc-to-production/', thumbnail: '/blog/ai-poc-to-production/card.webp'
    },
    {
        slug: 'rag-data-preparation',
        title: '社内文書をAI検索する前に。RAGの精度を左右するデータ整理の実務',
        date: '2026-07-10', publishAt: '2026-07-10T10:00:00+09:00', status: 'published', category: 'Development',
        description: '社内規程やマニュアルを生成AIで検索するRAG。精度を左右する重複、版管理、権限、文書構造、評価質問の整え方を実務目線で解説します。',
        excerpt: '社内文書を読み込ませるだけでは、実務に耐えるAI検索にはなりません。RAGの精度を左右するデータ整理と評価の進め方を解説します。',
        url: 'https://spacegleam.co.jp/blog/rag-data-preparation/', thumbnail: '/blog/rag-data-preparation/card.webp'
    },
    {
        slug: 'after-ai-development-diagnosis',
        title: 'AI開発診断の結果、次に何をする？社内検討を前に進める5つの整理',
        date: '2026-07-09', publishAt: '2026-07-09T10:00:00+09:00', status: 'published', category: 'Business',
        description: 'AI開発診断で方向性が見えた後、社内検討や開発相談へ進むために整理したい目的・対象業務・利用者・データ・判断条件を具体例とともに解説します。',
        excerpt: 'AI開発診断の結果を見た後、何をすればよいのか。診断結果を自社の業務へ置き換え、社内説明や開発相談を前に進める5つの整理を紹介します。',
        url: 'https://spacegleam.co.jp/blog/after-ai-development-diagnosis/', thumbnail: '/blog/after-ai-development-diagnosis/card.webp'
    },
    {
        slug: 'ai-automation-first-process',
        title: 'AIで自動化する業務、最初の1つはどう選ぶ？失敗しない優先順位の決め方',
        date: '2026-07-08', publishAt: '2026-07-08T10:00:00+09:00', status: 'published', category: 'Business',
        description: 'AIによる業務自動化は、対象業務の選び方で成果が変わります。頻度・時間・判断の複雑さ・例外・データの5項目から、最初に着手すべき業務を見極める方法を解説します。',
        excerpt: '何からAIで自動化するべきか。頻度、手順、確認、例外、データの5項目から、費用対効果が出やすい最初の業務を選ぶ方法を解説します。',
        url: 'https://spacegleam.co.jp/blog/ai-automation-first-process/', thumbnail: '/blog/ai-automation-first-process/card.webp'
    },
    {
        slug: 'ai-adoption-failed-fix',
        title: '「AIを導入したが、社内に浸透しない」という失敗を防ぐ、AI定着のための4つのステップ',
        date: '2026-07-06',
        publishAt: '2026-07-06T10:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: 'AIツールを導入したものの、社内で活用が進まない企業は少なくありません。定着を阻む「3つの壁」と、それを乗り越えて業務改善に繋げるための4つの実践的ステップについて解説します。',
        excerpt: 'AIツールを導入したものの、社内で活用が進まない企業は少なくありません。定着を阻む「3つの壁」と、それを乗り越えて業務改善に繋げるための4つの実践的ステップについて解説します。',
        url: 'https://spacegleam.co.jp/blog/ai-adoption-failed-fix/',
        thumbnail: '/blog/ai-adoption-failed-fix/card.webp'
    },
    {
        slug: 'custom-crm-sfa-versus-saas',
        title: 'Excelや汎用SaaSの限界。独自業務に合わせた「自社専用AIシステム」へ移行する判断基準',
        date: '2026-07-05',
        publishAt: '2026-07-05T10:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: '高額なSaaSを導入しても、結局Excelでの運用に戻ってしまう企業は多いです。汎用SaaSの限界と、生成AI時代に「自社専用の業務システム」をカスタム開発すべき判断基準を解説します。',
        excerpt: '高額なSaaSを導入しても、結局Excelでの運用に戻ってしまう企業は多いです。汎用SaaSの限界と、生成AI時代に「自社専用の業務システム」をカスタム開発すべき判断基準を解説します。',
        url: 'https://spacegleam.co.jp/blog/custom-crm-sfa-versus-saas/',
        thumbnail: '/blog/custom-crm-sfa-versus-saas/card.webp'
    },
    {
        slug: 'ai-development-security-guide',
        title: '「API経由のデータは学習されない」は本当？企業が生成AIシステムを開発する際に知っておくべきセキュリティと情報管理の基本',
        date: '2026-07-04',
        publishAt: '2026-07-04T10:00:00+09:00',
        status: 'published',
        category: 'Development',
        description: '「社内データや顧客情報が漏洩するのではないか」という不安からAI開発に踏み切れない企業向けに、ChatGPT等のAPI接続のデータ処理の真実と、安全なシステム設計手法を分かりやすく解説します。',
        excerpt: '「社内データや顧客情報が漏洩するのではないか」という不安からAI開発に踏み切れない企業向けに、API接続のデータ処理の真実と、安全なシステム設計手法を分かりやすく解説します。',
        url: 'https://spacegleam.co.jp/blog/ai-development-security-guide/',
        thumbnail: '/blog/ai-development-security-guide/card.webp'
    },
    {
        slug: 'ai-product-mvp-value',
        title: '“AIを載せただけ”にならない新規事業の設計方法。失敗するサービスと、真の顧客価値を生むプロダクトの違い',
        date: '2026-07-03',
        publishAt: '2026-07-03T10:00:00+09:00',
        status: 'published',
        category: 'Product',
        description: 'AIブームの中で「AI搭載」を謳うも使われないサービスが増えています。新規事業を成功させるために、AIありきではなく顧客課題から逆算するMVP（最小限の製品）開発の正しいアプローチを解説します。',
        excerpt: 'AIブームの中で「AI搭載」を謳うも使われないサービスが増えています。新規事業を成功させるために、AIありきではなく顧客課題から逆算するMVP開発の正しいアプローチを解説します。',
        url: 'https://spacegleam.co.jp/blog/ai-product-mvp-value/',
        thumbnail: '/blog/ai-product-mvp-value/card.webp'
    },
    {
        slug: 'how-to-write-ai-rfp',
        title: '失敗しない「AIシステム開発」のRFP（提案依頼書）の書き方と、開発会社を見極める3つのポイント',
        date: '2026-07-02',
        publishAt: '2026-07-02T10:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: 'AIシステム外注の成否は「RFP（提案依頼書）」の書き方で決まります。精度やデータの定義などAI開発特有の書き方と、開発会社の提案・見積もりを比較する際の重要なチェックポイントを解説します。',
        excerpt: 'AIシステム外注の成否は「RFP（提案依頼書）」の書き方で決まります。精度やデータの定義などAI開発特有の書き方と、開発会社の提案・見積もりを比較する際の重要なチェックポイントを解説します。',
        url: 'https://spacegleam.co.jp/blog/how-to-write-ai-rfp/',
        thumbnail: '/blog/how-to-write-ai-rfp/card.webp'
    },
    {
        slug: 'ai-era-business-judgment',
        title: 'AI時代に企業が失うものは「情報」ではなく「判断力」かもしれない',
        date: '2026-06-21',
        publishAt: '2026-06-21T00:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: 'AIが情報収集や分析を担う時代、企業にとって本当に重要なのは「情報を持っているか」ではなく「判断できるか」です。本記事では、AI時代に企業が見落としがちな判断力の重要性と、それをどう守り育てるかについて解説します。',
        excerpt: 'AIが情報収集や分析を担う時代、企業にとって本当に重要なのは「情報を持っているか」ではなく「判断できるか」です。AI時代に企業が見落としがちな判断力の重要性について解説します。',
        url: 'https://spacegleam.co.jp/blog/ai-era-business-judgment/',
        thumbnail: '/blog/ai-era-business-judgment/card.webp'
    },
    {
        slug: 'ai-small-team-productivity',
        title: 'AIを使う会社は、なぜ少ない人数でも仕事が進むのか？',
        date: '2026-06-20',
        publishAt: '2026-06-20T00:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: '生成AIの活用によって、少人数でも企画・調査・資料作成・開発・情報整理を進めやすい時代になっています。本記事では、SPACE GLEAMが実際にClaude Code、Gemini、ChatGPTなどを活用しながら受託開発や自社サービス開発を進めている実例をもとに、AIが企業の仕事の進め方をどう変えているのかを解説します。',
        excerpt: '生成AIの活用によって、少人数でも企画・調査・資料作成・開発・情報整理を進めやすい時代に。SPACE GLEAMがClaude Code・Gemini・ChatGPTを活用しながら開発を進める実例から解説します。',
        url: 'https://spacegleam.co.jp/blog/ai-small-team-productivity/',
        thumbnail: '/blog/ai-small-team-productivity/card.webp'
    },
    {
        slug: 'free-ai-development-diagnosis',
        title: 'AI開発診断を公開しました。30秒で開発の方向性が見えてくる無料診断です',
        date: '2026-06-19',
        publishAt: '2026-06-19T00:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: '「AIを活用したい」「業務を効率化したい」「サービスを作りたい」。そう考えたとき、多くの方が最初に悩むのは技術ではなく“何から始めるべきか”です。SPACE GLEAMでは、開発の方向性や予算感、進め方を整理できるAI開発診断を公開しました。本記事では、診断を作った背景と診断で分かることをご紹介します。',
        excerpt: 'SPACE GLEAMでは、開発の方向性や予算感、進め方を整理できるAI開発診断を公開しました。30秒で開発の方向性が見えてくる無料診断です。',
        url: 'https://spacegleam.co.jp/blog/free-ai-development-diagnosis/',
        thumbnail: '/blog/free-ai-development-diagnosis/card.webp'
    },
    {
        slug: 'why-custom-business-systems-are-growing',
        title: 'なぜ今、自社専用の業務システムを持つ企業が増えているのか？',
        date: '2026-06-18',
        publishAt: '2026-06-18T00:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: '以前は業務システムの開発といえば、大企業だけが取り組める高額な投資でした。しかし生成AIの登場によって、企業ごとの業務に合わせたシステムを、これまでよりも現実的なコストで構築できる時代になっています。本記事では、既製品のSaaSだけでは解決できない課題と、自社専用システムを持つメリット、そしてAI時代ならではの新しい開発の考え方について解説します。',
        excerpt: '以前は業務システムの開発といえば、大企業だけが取り組める高額な投資でした。しかし生成AIの登場によって、企業ごとの業務に合わせたシステムを、これまでよりも現実的なコストで構築できる時代になっています。',
        url: 'https://spacegleam.co.jp/blog/why-custom-business-systems-are-growing/',
        thumbnail: '/blog/why-custom-business-systems-are-growing/card.webp'
    },
    {
        slug: 'why-business-systems-fail-and-how-ai-solves-it',
        title: 'なぜ多くの業務システムは使われなくなるのか？AI開発で解決できる本当の課題',
        date: '2026-06-17',
        publishAt: '2026-06-17T00:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: '多くの企業が業務システムを導入しても、数か月後にはExcelやチャットでの運用に戻ってしまいます。問題はシステムの性能ではなく、業務とのズレにあります。本記事では、なぜ業務システムが定着しないのか、その原因とAI開発による解決方法について解説します。',
        excerpt: '多くの企業が業務システムを導入しても、数か月後にはExcelやチャットでの運用に戻ってしまいます。問題はシステムの性能ではなく、業務とのズレにあります。本記事では、なぜ業務システムが定着しないのか、その原因とAI開発による解決方法について解説します。',
        url: 'https://spacegleam.co.jp/blog/why-business-systems-fail-and-how-ai-solves-it/',
        thumbnail: '/blog/why-business-systems-fail-and-how-ai-solves-it/card.webp'
    },
    {
        slug: 'is-ai-generated-software-secure',
        title: 'AIで作ったシステムは本当に安全なのか？ 生成AI時代だからこそ重要になる「運用品質」',
        date: '2026-06-16',
        publishAt: '2026-06-16T00:00:00+09:00',
        status: 'published',
        category: 'Development',
        description: 'ChatGPTやClaudeなどの生成AIの進化によって、システム開発のスピードは飛躍的に向上しました。しかし「AIで作ったから安全」と考えるのは危険です。npmハックやサプライチェーン攻撃の実例を交えながら、AI開発時代に求められるセキュリティと運用品質を解説します。',
        excerpt: 'ChatGPTやClaudeなどの生成AIの進化によって、システム開発のスピードは飛躍的に向上しました。しかし「AIで作ったから安全」「AIが書いたコードだから品質が高い」と考えるのは危険です。npmハックやサプライチェーン攻撃の実例を交えながら、AI開発時代に求められる運用品質を解説します。',
        url: 'https://spacegleam.co.jp/blog/is-ai-generated-software-secure/',
        thumbnail: '/blog/is-ai-generated-software-secure/card.webp'
    },
    {
        slug: 'ai-adoption-gap',
        title: 'AIを使う企業と使わない企業の差',
        date: '2026-06-15',
        publishAt: '2026-06-15T00:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: 'AIの普及によって、多くの企業が業務効率化を検討するようになりました。しかし実際には、積極的に活用を進める企業と、様子見を続ける企業に分かれています。その差はAIツールの性能ではありません。企業の中に蓄積される経験値です。本記事では、AIを使う企業が実際に何を手に入れているのかを解説します。',
        excerpt: 'AIの普及によって、多くの企業が業務効率化を検討するようになりました。しかし実際には、積極的に活用を進める企業と、様子見を続ける企業に分かれています。その差はAIツールの性能ではありません。企業の中に蓄積される経験値です。',
        url: 'https://spacegleam.co.jp/blog/ai-adoption-gap/',
        thumbnail: '/blog/ai-adoption-gap/card.webp'
    },
    {
        slug: 'will-todays-ai-companies-survive',
        title: '5年後、今のAI企業は残っているのか。それでも今AI投資を始めるべき理由',
        date: '2026-06-12',
        publishAt: '2026-06-12T12:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: 'OpenAI、Anthropic、Google Geminiなど、現在の生成AI市場を牽引する企業は今後も存在し続けるのでしょうか。実際のところ、それは誰にも分かりません。しかしAI活用そのものは今後さらに広がる可能性が高いと考えられます。本記事では、AI企業の将来ではなく「AIを活用する企業になること」が重要な理由について解説します。',
        excerpt: 'OpenAI、Anthropic、Google Geminiなど、現在の生成AI市場を牽引する企業は今後も存在し続けるのでしょうか。実際のところ、それは誰にも分かりません。しかしAI活用そのものは今後さらに広がる可能性が高いと考えられます。本記事では、AI企業の将来ではなく「AIを活用する企業になること」が重要な理由について解説します。',
        url: 'https://spacegleam.co.jp/blog/will-todays-ai-companies-survive/',
        thumbnail: '/blog/will-todays-ai-companies-survive/card.webp'
    },
    {
        slug: 'diffsense-three-days',
        title: 'なぜDIFFsenseは3日で作れたのか',
        date: '2026-06-11',
        publishAt: '2026-06-11T12:00:00+09:00',
        status: 'published',
        category: 'Product',
        description: 'DIFFsenseは、契約書や利用規約の変更をAIで比較・管理するサービスです。現在では、AI差分比較、AI要約、URL監視、電子署名、通知機能など複数の機能を提供しています。しかし最初からこの形だったわけではありません。実はDIFFsen...',
        excerpt: 'DIFFsenseは、契約書や利用規約の変更をAIで比較・管理するサービスです。現在では、AI差分比較、AI要約、URL監視、電子署名、通知機能など複数の機能を提供しています。しかし最初からこの形だったわけではありません。実はDIFFsen...',
        url: 'https://spacegleam.co.jp/blog/diffsense-three-days/',
        thumbnail: '/blog/assets/n2585507fcce6_card.webp'
    },
    {
        slug: 'ai-development-outsourcing',
        title: 'AI開発を外注するメリット｜内製との違いと失敗しない進め方',
        date: '2026-06-10',
        publishAt: '2026-06-10T12:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: 'AIの活用が広がる中で、「AIを使った業務効率化を進めたい」「自社サービスにAI機能を組み込みたい」と考える企業が増えています。その一方で、「社内で開発するべきか、それとも外注するべきか」という悩みを抱えるケースも少なくありません。結論から...',
        excerpt: 'AIの活用が広がる中で、「AIを使った業務効率化を進めたい」「自社サービスにAI機能を組み込みたい」と考える企業が増えています。その一方で、「社内で開発するべきか、それとも外注するべきか」という悩みを抱えるケースも少なくありません。結論から...',
        url: 'https://spacegleam.co.jp/blog/ai-development-outsourcing/',
        thumbnail: '/blog/assets/n4de10aef1158_card.webp'
    },
    {
        slug: 'ai-development-real-bottleneck',
        title: 'AI開発で一番時間がかかったのはAIではなかった',
        date: '2026-06-09',
        publishAt: '2026-06-09T12:00:00+09:00',
        status: 'published',
        category: 'Development',
        description: 'AIサービスを作っていると言うと、よく聞かれることがあります。「やっぱりAIの部分が一番大変なんですか？」実は違います。もちろんAIにも難しさはあります。しかし、複数のAIサービスを企画・開発・運営してきた中で感じるのは、AIは意外と早く動...',
        excerpt: 'AIサービスを作っていると言うと、よく聞かれることがあります。「やっぱりAIの部分が一番大変なんですか？」実は違います。もちろんAIにも難しさはあります。しかし、複数のAIサービスを企画・開発・運営してきた中で感じるのは、AIは意外と早く動...',
        url: 'https://spacegleam.co.jp/blog/ai-development-real-bottleneck/',
        thumbnail: '/blog/assets/n6050e37f96fa_card.webp'
    },
    {
        slug: 'no-more-throwaway-mvp',
        title: 'もう「作り捨ての試作品」に、お金と時間をかけなくていい',
        date: '2026-06-08',
        publishAt: '2026-06-08T10:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: 'これまでの開発では、まず安く小さく試作し、後から作り直すのが常識でした。AIによってこの前提は変わります。最初から本番品質で作れる時代の、新しい開発の進め方をお伝えします。',
        excerpt: 'これまでの開発では、まず安く小さく試作し、後から作り直すのが常識でした。AIによってこの前提は変わります。最初から本番品質で作れる時代の、新しい開発の進め方をお伝えします。',
        url: 'https://spacegleam.co.jp/blog/no-more-throwaway-mvp/',
        thumbnail: '/blog/assets/n52ecb67c16f3_card.webp'
    },
    {
        slug: 'ai-mvp-first-decisions',
        title: 'AI受託開発の費用相場と、失敗しない会社の選び方【2026年版】',
        date: '2026-06-04',
        publishAt: '2026-06-04T10:00:00+09:00',
        status: 'published',
        category: 'Business',
        description: 'AI受託開発の費用相場は、PoCで数十万〜300万円、中規模システムで300万〜1,000万円が一般的。でも2026年, AIを使った開発なら25万円〜・最短2〜4週間で"いきなり商用レベル"が作れる時代になりました。ただし「安いから」で選ぶと本番で苦労します。この記事では費用相場・なぜ安くなったのか・失敗しないAI開発会社の選び方を、自社でSaaSを運用する立場から正直に解説します。',
        excerpt: 'AI受託開発の費用相場は、PoCで数十万〜300万円、中規模システムで300万〜1,000万円が一般的。でも2026年, AIを使った開発なら25万円〜・最短2〜4週間で"いきなり商用レベル"が作れる時代になりました。',
        url: 'https://spacegleam.co.jp/blog/ai-mvp-first-decisions/',
        thumbnail: '/blog/assets/naeb8187a566e_card.webp'
    },
    {
        slug: 'why-space-gleam-builds-own-services',
        title: 'なぜSPACE GLEAMは自社サービスを作り続けるのか',
        date: '2026-06-02',
        publishAt: '2026-06-02T00:00:00+09:00',
        status: 'published',
        category: 'Product',
        description: 'SPACE GLEAMが自社サービスを作り続ける理由と、運営から得られる知見、AI時代のプロダクトづくりへの考え方を紹介します。',
        excerpt: 'SPACE GLEAMは単なる開発会社ではなく、自社サービスを企画・開発・運営しながら、作る、運営する、改善するサイクルを続けています。',
        url: 'https://spacegleam.co.jp/blog/why-space-gleam-builds-own-services/',
        thumbnail: '/blog/assets/nce9566eed6ea_card.webp'
    }
];
